<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\FrontController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\Controller.php';
include_once $this->targetDirs[3].'\\src\\Controller\\FrontController.php';

return $this->services['App\Controller\FrontController'] = new \App\Controller\FrontController(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')), ($this->privates['App\Repository\TypedebienRepository'] ?? $this->load('getTypedebienRepositoryService.php')), ($this->privates['App\Repository\ArrondissementRepository'] ?? $this->load('getArrondissementRepositoryService.php')), ($this->privates['App\Repository\BienRepository'] ?? $this->load('getBienRepositoryService.php')), ($this->privates['App\Repository\ImageRepository'] ?? $this->load('getImageRepositoryService.php')));
