security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\User, property: email }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # les urls auxquels s'appliquent ce firewall, dans ce cas, ce sont toutes les urls
            pattern: ^/

            # La connexion n'est pas requise sur toutes les pages
            # par exemple la page d'accueil
            anonymous: true

            form_login:
                # Le nom de la route de la page de connexion
                check_path: security_login
                # Le nom de la route où se trouve le formulaire de connexion
                # Si un utilisateur tente d'acceder à une page protégée sans en avoir les droits
                # il sera redirigé sur cette page
                login_path: security_login
                # Securisation des formulaires
                csrf_token_generator: security.csrf.token_manager
                # La page par defaut apres une connexion reussie
                default_target_path: after_login

            logout:
                # La route où se trouve le process de deconnexion
                path: security_logout
                # La route sur laquelle doit etre rediriger l'utilisateur apres une deconnexion
                target: after_logout

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path:     /
                # Par défaut, la fonctionnalité est activée en vérifiant un case à cocher dans le formulaire de connexion
                # Décommentez le ligne suivante pour toujours l'activer
                #<input type="checkbox" id="remember_me" name="_remember_me" checked />
                #always_remember_me: true

    access_control:
        # Les regles de securité
        # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
        # peuvent acceder à toutes les pages commençant par /admin

        - { path: '^/back', roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: '^/account', roles: [ROLE_USER, ROLE_PROPRIETAIRE] }
        - { path: '^/front', roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
