<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVwXn9j7\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVwXn9j7/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVwXn9j7.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerVwXn9j7\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerVwXn9j7\srcProdProjectContainer(array(
    'container.build_hash' => 'VwXn9j7',
    'container.build_id' => 'bcf5b965',
    'container.build_time' => 1532600026,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVwXn9j7');
