<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FngfaY1' shared service.

return $this->privates['.service_locator.FngfaY1'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('eventDispatcher' => function () {
    return ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService());
}, 'helper' => function () {
    return ($this->services['security.authentication_utils'] ?? $this->load('getSecurity_AuthenticationUtilsService.php'));
}));
