<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAx4kxO9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAx4kxO9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAx4kxO9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAx4kxO9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAx4kxO9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ax4kxO9',
    'container.build_id' => 'b2db5519',
    'container.build_time' => 1534754996,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAx4kxO9');
