<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT4Yu28j\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT4Yu28j/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT4Yu28j.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT4Yu28j\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerT4Yu28j\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'T4Yu28j',
    'container.build_id' => 'd045c5f4',
    'container.build_time' => 1536502746,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT4Yu28j');
